[package]
name = "harness"
version = "0.1.0"
edition = "2021"
description = "Precise and reproducible micro benchmarking"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cargo-harness"
path = "src/runner/main.rs"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
cargo_metadata = "0.18.0"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
env_logger = "0.10.0"
harness-macros = { path = "./macros" }
libloading = "0.8.1"
log = "0.4.20"

[workspace]
members = [".", "macros", "example-crate", "probes/perf"]
