[package]
name = "harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "cargo-harness"
path = "src/bin/runner.rs"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
cargo_metadata = "0.18.0"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
harness-macros = { path = "./macros" }
