[package]
name = "example-crate"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"

[dev-dependencies]
harness = { path = ".." }

[features]
default = []
node_enqueuing = []
edge_enqueuing = []

[[bench]]
name = "trace"
harness = false

[package.metadata.harness.profiles.default.build-variants]
node_enqueuing = { features = ["node_enqueuing"] }
edge_enqueuing = { features = ["edge_enqueuing"] }
