[package]
name = "example-crate"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
harness = { path = ".." }

[features]
default = []
rec = []

[[bench]]
name = "fib"
harness = false

[package.metadata.harness.profiles.default.build-variants]
rec = { features = ["rec"] }
iter = {}
